# Generated by Django 5.0.8 on 2024-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dev_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='test_count',
            field=models.IntegerField(default=0),
        ),
    ]
