# Generated by Django 5.0.8 on 2024-08-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank nomi')),
                ('bank_info', models.TextField(verbose_name='Bank haqida')),
                ('bank_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank manzili')),
                ('bank_image', models.ImageField(blank=True, null=True, upload_to='bank_images/', verbose_name='Bank rasmi')),
                ('bank_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank telefon raqami')),
                ('bank_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank emaili')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
