# Generated by Django 5.0.8 on 2024-08-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='examtest',
            name='test_answer',
        ),
        migrations.AddField(
            model_name='examtest',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri javobmi"),
        ),
        migrations.AddField(
            model_name='examtest',
            name='science',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_panel.science', verbose_name='Fan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examtest',
            name='selected_answer',
            field=models.CharField(default=1, max_length=255, verbose_name='Tanlangan javob'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_panel.science', verbose_name='Fan'),
        ),
    ]
